userdata: |
  echo ECS_CLUSTER=${EcsCluster} >> /etc/ecs/ecs.config
  INSTANCE_ID=$(/opt/aws/bin/ec2-metadata --instance-id|/usr/bin/awk '{print $2}')
  hostname ${EnvironmentName}-ecs-${!INSTANCE_ID}
  sed '/HOSTNAME/d' /etc/sysconfig/network > /tmp/network && mv -f /tmp/network /etc/sysconfig/network && echo "HOSTNAME=${EnvironmentName}-ecs-${!INSTANCE_ID}\" >>/etc/sysconfig/network && /etc/init.d/network restart
  iptables --insert FORWARD 1 --in-interface docker+ --destination 169.254.169.254/32 --jump DROP
  iptables-save
  echo "Done"


default_tags:
  - Key: Name
    Value:
      Fn::Sub: ${EnvironmentName}-ecs-mixed-asg
  - Key: Environment
    Value:
      Fn::Sub: ${EnvironmentName}
  - Key: EnvironmentType
    Value:
      Fn::Sub: ${EnvironmentType}