enable_efs: false

detailed_monitoring: false

terminate_excess: false

iam_policies:
  ecs-container-instance:
    action:
      - ecs:CreateCluster
      - ecs:DeregisterContainerInstance
      - ecs:DiscoverPollEndpoint
      - ecs:Poll
      - ecs:RegisterContainerInstance
      - ecs:StartTelemetrySession
      - ecs:Submit*
      - ecr:GetAuthorizationToken
      - ecr:BatchCheckLayerAvailability
      - ecr:GetDownloadUrlForLayer
      - ecr:BatchGetImage
      - logs:CreateLogStream
      - logs:PutLogEvents
  ecs-service-scheduler:
    action:
      - ec2:AuthorizeSecurityGroupIngress
      - ec2:Describe*
      - elasticloadbalancing:DeregisterInstancesFromLoadBalancer
      - elasticloadbalancing:DeregisterTargets
      - elasticloadbalancing:Describe*
      - elasticloadbalancing:RegisterInstancesWithLoadBalancer
      - elasticloadbalancing:RegisterTargets
  ssm-ssh-access:
    action:
      - ssm:UpdateInstanceInformation
      - ssm:ListInstanceAssociations
      - ec2messages:GetMessages
      - ssmmessages:CreateControlChannel
      - ssmmessages:CreateDataChannel
      - ssmmessages:OpenControlChannel
      - ssmmessages:OpenDataChannel


userdata: |
  INSTANCE_ID=$(/opt/aws/bin/ec2-metadata --instance-id|/usr/bin/awk '{print $2}')
  hostname ${EnvironmentName}-ecs-${!INSTANCE_ID}
  sed '/HOSTNAME/d' /etc/sysconfig/network > /tmp/network && mv -f /tmp/network /etc/sysconfig/network && echo "HOSTNAME=${EnvironmentName}-ecs-${!INSTANCE_ID}\" >>/etc/sysconfig/network && /etc/init.d/network restart

efs_mount: |
  mkdir /efs
  yum install -y nfs-utils
  mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 ${FileSystem}.efs.${AWS::Region}.amazonaws.com:/ /efs

# cfnsignal: |
#   /opt/aws/bin/cfn-signal --exit-code $? \
#            --stack  ${AWS::StackName} \
#            --resource AutoScaleGroup  \
#            --region ${AWS::Region}
